### ISSUE TITLE
[1.80pr0][Feature Request]Mining Turtle & Grass Path block.

### ISSUE THREAD

**Issue by Nokiyen** [dan200/ComputerCraft#127]
This is not a bug, but feature request.
### Expected

Digging Turtle changes Grass Block into Grass Path Block with turtle.dig() function.
### Actual

The Turtle returns false in the above situation.
### Detail

From 1.9, "Grass Path" block is added. It can be created from Grass block by right clicking with Spade.
So, naturally, Digging Turtle should create Grass Path block from Grass block by dig() function as Farming Turtle can create Farmland block.

(And now, a player make Grass Path block change into Farmland block by right clicking with Hoe...)

**Comment by apemanzilla** [comment]
I think this would make sense but only if it were Digging Turtles (with shovels) that can make grass paths. It would also give them a use over the all-powerful Mining Turtles.

**Comment by Nokiyen** [comment]
Ah! I just mistook Digging Turtle and Mining Turtle! Digging Turtle is correct. I edited original replay...
Thanks!

**Comment by Restioson** [comment]
Do the above commits warrant this closed?

**Comment by SquidDev** [comment]
No - I haven't put forward a PR because I'm not happy with either of them. There are still a couple of things about the existing implementation that I'm not sure about, namely:

 - Hoeing/shovelling dirt will attempt to transform the block one block away, two blocks away and one block away and then down. This makes sense for `turtle.place()` but not here - I think it would be better if it just did one block away and one block away and down (which allows for hoeing/shovelling the block below you).
 - `TurtlePlaceEvent.deploy` is too general for the tool - technically `turtle.dig()` with a hoe/shovel will also attempt to right click entities in front of it, as well as triggering block's own right click methods. Ideally it would call just the sufficient methods to hoe/flatten dirt.
 - `PlayerInteractEvent.RightClickBlock` is not fired. There [are mods](https://minecraft.curseforge.com/projects/dirt2path) which allow the shovel to convert normal dirt to path blocks, using this event. Firing it would allow these mods to function as expected.

**Comment by dan200** [comment]
This behaviour seems similar to what the farming turtle already does with
dirt, perhaps mirror that?

**Comment by SquidDev** [comment]
@dan200 My second attempt at this (SquidDev-CC/ComputerCraft@93aea371a70711fde5f249c3db0999a3dc69452a) does that. However, there are a couple of things I'm not sure about as mentioned in my previous comment. I'm happy to PR it though if you're OK with it as is.

**Comment by dan200** [comment]
I would be happy to merge that PR. It's better for the rules to be Consistent with placing and hoeing than not.
