### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in Lua script

### ISSUE THREAD

**Issue by NexAdn** [dan200/ComputerCraft#141]
Well, I can just say that this error occurs every time I start my script. It always prints me

`java.lang.ArrayIndexOutOfBoundsException`

Being a Java Exception it should be an error of CC itself.
This is the script that made the error occur: https://github.com/NexAdn/cpm/blob/development/cpm.lua

I'm using CC1.79

**Comment by dan200** [comment]
This script is far too long for me to use. Please try to narrow down the
code to the line which is causing the error.

**Comment by SquidDev** [comment]
Generally this means there is a stack overflow in your Lua code: put this on the CC forums for debugging help. I *think* the LuaJ bug exists because there are no bounds checks in the debug library: they are meant to be called in the LuaThread's stack but the debug library's method gets called first.

**Comment by NexAdn** [comment]
This is the function that seems to throw the Java Exception. It's thrown when checkInitial() is called.
https://gist.github.com/NexAdn/8dfc2d1962cb06b7899068651d649784

**Comment by AEnterprise** [comment]
check your initConfDir dir, most likely that isn't working causing an infinite recursive loop

**Comment by NexAdn** [comment]
Hm. The function didn't do what it was supposed to do. That caused the error.
