### ISSUE TITLE
Request: Open Source

### ISSUE THREAD

**Issue by greencopper** [dan200/ComputerCraft#151]
Hi

Would you please consider open sourcing Computercraft?

We're a lot of people who would like to contribute and the development is very slow - which is understandable.

Open sourcing Computercraft makes a lot of sense. It's free (cost no money) anyway and by opening it up you would get help from other people.

Anyway, thanks for a great mod!

Kind regards

**Comment by jordyvl** [comment]
Opensourcing would also mean that he does not have any way to monitor if the changes other people make are any good





---- On wo, 22 feb 2017 19:12:37 +0100 greencopper &lt;notifications@github.com&gt; wrote ----




Hi

Would you please consider open sourcing Computercraft?

We're a lot of people who would like to contribute and the development is very slow - which is understandable.

Open sourcing Computercraft makes a lot of sense. It's free (cost no money) anyway and by opening it up you would get help from other people.

Anyway, thanks for a great mod!

Kind regards

**Comment by Pyeroh** [comment]
Pull request ? If he's the only reviewer and contributor of his repo, then he's the only who can approve official code modifications.

**Comment by jordyvl** [comment]
Then hè would be busy with that all the Day do not think hè would like to do that but i could be wrong 


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Pyeroh <notifications@github.com> 
Datum: 23-02-17  09:44  (GMT+01:00) 
Aan: dan200/ComputerCraft <ComputerCraft@noreply.github.com> 
Cc: Jordy van laerhoven <jordy@ccmaster.nl>, Comment <comment@noreply.github.com> 
Onderwerp: Re: [dan200/ComputerCraft] Request: Open Source (#151) 

Pull request ? If he's the only reviewer and contributor of his repo, then he's the only who can approve official code modifications.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dan200/ComputerCraft","title":"dan200/ComputerCraft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dan200/ComputerCraft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Pyeroh in #151: Pull request ? If he's the only reviewer and contributor of his repo, then he's the only who can approve official code modifications."}],"action":{"name":"View Issue","url":"https://github.com/dan200/ComputerCraft/issues/151#issuecomment-281930411"}}}

**Comment by apemanzilla** [comment]
It doesn't take all day to review pull requests. It takes minutes. And that's only when there are pull requests to review and merge...

**Comment by jordyvl** [comment]
well it is his choice, But if i was him i would not do it just because 
everyone will overwrite each other and i still believe it is not any 
improvement at all but that is how i see it


Op 24-2-2017 om 5:28 schreef apemanzilla:

**Comment by apemanzilla** [comment]
@jordyvl That's not at all how open source works. Versioning systems like Git are carefully designed to avoid that issue. Just look at how many open source projects there are here on GitHub.

**Comment by vpontin** [comment]
Maybe sharing the PR moderation and core contribuitions with you @SquidDev could be a great thing

**Comment by Keanu73** [comment]
@SquidDev I believe he should get a rest too, but right now he's lounging on his chair waiting for monetary revenue. I'm serious. http://prntscr.com/egdi17

**Comment by SquidDev** [comment]
@Keanu73 OK, seriously? If you've been following Dan's twitter you'd have seen he's hard at work getting Redirection running as well as possible on mobile devices. That is hardly "lounging" about in anyone's books.

Secondly, ComputerCraft is developed for free in Dan's spare time should he want to. He owes you **nothing**. Complaining here or (on twitter) about the fact that he isn't working on ComputerCraft is rude and entitled. It also is incredibly demotivating: whilst I can't speak for Dan, personally the more people bug me to update the less likely I'm going to do it - you just get tired of people asking and go and work on something else.

**Comment by apemanzilla** [comment]
Here's the original comment that was deleted by Keanu73, for archival purposes.

>@SquidDev I believe he should get a rest too, but right now he's lounging on his chair waiting for monetary revenue. I'm serious. http://i.imgur.com/lfbkNIy.png

**Comment by smickles** [comment]
Damn, I went away from MC for a bit and have come back and wanted to play the current (or a recent) release with ComputerCraft.

I don't mind someone stopping working on something. But it's saddening to see it get killed off w/o the source being released in some capacity.

**Comment by SquidDev** [comment]
@smickles Whilst Dan is moving away from ComputerCraft development, he [has plans](https://twitter.com/DanTwoHundred/status/840290866883366913) to open source the mod. From what I can tell, [he still plans to make occasional releases](https://www.reddit.com/r/feedthebeast/comments/5yyx3c/computercraft_is_going_opensource_and_dan200_is/devth7s/?context=3) too.

### A collection of relevant quotes:
> As for ComputerCraft itself: it's no secret that I haven't had time to work on it in a while. So my plan is to open source the mod soon.

> It's been 5 and a half years since I wrote the first line of CC code, and while it's been life changing, it's time to put down the pickaxe.

>  I'll still be reviewing and accepting pull requests and making releases from the "official" repository. I haven't decided yet whether the license I choose will permit others to release competing forks.

> I've been pretty happy with the core feature set in ComputerCraft for a while now, so i'm mostly thinking of this release in terms of version updates and bug fixes.

**Comment by dan200** [comment]
Resolved :D

**Comment by JLLeitschuh** [comment]
I really want to dig into this code and play with it.
This is a mod I played with years ago and always enjoyed.
Thank you so much for releasing it!!!

**Comment by Wojbie** [comment]
So this has happened. Time to see if community with do what it promised to do.
