### ISSUE TITLE
Automatically Close File Handles

### ISSUE THREAD

**Issue by Restioson** [dan200/ComputerCraft#189]
In release 1.8.9, if you do not close a file handle, or terminate the program before it has closed the handle, you cannot edit the file. It would be nice it was closed when the program which owns the handle is terminated.

**Comment by SquidDev** [comment]
I'd rather people just closed file handles, but I realise bugs happen 😄. Instead of closing it when the program terminates (which isn't really feasible), it would probably be better to close it when the handle is garbage collected. This could probably be done with a `ReferenceQueue` and a weak reference to the `IMountedFile`.

**Comment by apemanzilla** [comment]
Could even be done with `Object.finalize`, but we don't talk about that.

**Comment by dan200** [comment]
This should be fixed in https://github.com/dan200/ComputerCraft/commit/09215daa03d7ccfa342d2508274805f3c575ff58
Previously, that HashSet was preventing the java GC from collecting lost file handles.
