### ISSUE TITLE
Wierd indirect redstone interactions.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#393]
It was recently pointed out to me and after some testing i found it to be the case.
When having setup like this:
![2017-07-30_13 42 31](https://user-images.githubusercontent.com/5893536/28753032-2c9896a0-752d-11e7-962d-f7295f6bfb93.png)
As in Computer - any full block - door.
If output is set to true on the side the door will open.
But setting output back to false on that side will not cause the door to close.
It works that way on all sides.
I did test that with repeated as on picture and blocks were getting powered correctly. 
It just seems like on indirect un-powereing doors ( and trapdoors) do not receive the redstone update?
Hopefully someone will be able to make more sense of this then me.

EDIT: Shutting computer down (whitch sets all redstone to false) has same effect.

**Comment by BombBloke** [comment]
Worth pointing out that the repeater *does* power down correctly, as do lamps, gates, and pistons. I can also reproduce with doors / trapdoors by having a "lit" turtle move away from the grass block instead of calling rs.setOutput(). Unlike [an older redstone related bug](http://www.computercraft.info/forums2/index.php?/topic/22889-fixed-as-of-176pr2173smpsspmoving-or-attempting-to-move-turtle-does-not-update-redstone/), toggling term.setCursorBlink() off / on seems to have no effect here.

Personally I'm testing under MC1.12.
