### ISSUE TITLE
Pasting characters 1 through 31 results in ?

### ISSUE THREAD

**Issue by heldplayer** [dan200/ComputerCraft#42]
Pasting in any character (except ¶ and §) in the ASCII range of 1 through 31 into a computer results in ?s to be displayed.

¶ works properly. § doesn't paste at all.

EDIT: clarified the description

**Comment by dan200** [comment]
When you say characters 0 to 31, which characters are you referring to? 0-31 are the ASCII control characters, none of which are typically printed besides how /t, /r and /n create whitespace.

**Comment by heldplayer** [comment]
Characters 0 through 31 are the first row of this picture: http://puu.sh/lS4Fc.png

Having typed the characters somewhere by doing alt+(num), then copying and pasting into a terminal resulted in a ?

(Character 0 can't actually be gotten using this method.)

**Comment by dan200** [comment]
The ComputerCraft font is basically ISO-8859-1, with extra graphical characters on the unused control characters. If you want to type characters, you'd have to input those control characters, which your keyboard probably doesn't let you do. Typing the unicode characters which happen to look like the glyphs i've drawn for said characters won't work, because those unicode characters (except the 2 you mentioned, are out of the ISO-8859-1 range)

**Comment by dan200** [comment]
(Basically, you have to print them from code, using string.char())

**Comment by dan200** [comment]
(fun fact: alt+num on windows actually looks up characters using their [Dos-437](https://en.wikipedia.org/wiki/Code_page_437) positions, not their unicode ones)
