### ISSUE TITLE
Global Functions?

### ISSUE THREAD

**Issue by bmccalmon** [dan200/ComputerCraft#556]
I cannot call a function from another lua file. Is the default changed to local?

**Comment by bmccalmon** [comment]
So do you suggest I write my OS in one main file? I always treated the separate lua files as separate classes. Now that I can't set global variables or functions I think otherwise.

**Comment by SquidDev** [comment]
You've got three options:

 - Don't use globals unless you absolutely have to. There are generally much nicer ways of sharing code or splitting it up, such as `require`.
 - Load code explicitly into the global environment, using something like `loadfile`.
 - Explicitly use `_G` (`_G.my_variable = xyz` (or `function _G.my_function() end`) in order to change global environment.

**Comment by apemanzilla** [comment]
To clarify, it's usually best to define your code as files which `return` anything you want to share - e.g. a table of functions. Then, you can use `local functions = require("file")` to load them from a different file.
