### ISSUE TITLE
using /fill or /clone renders computers and monitors unuseable

### ISSUE THREAD

**Issue by PokemonInLua** [dan200/ComputerCraft#62]
So how this works is if either /fill or /clone is used in THE SAME chunk a monitor/computer is in, it can not be used until the chunks are reloaded.

Reproduction steps:

1. place a computer
2. place a multiblock monitor (easier to see)
3. use /fill or /clone (not replacing the computer and/or monitor)
4. they are now unuseable
5. do /tp ~ ~ ~500
6. do /tp ~ ~ ~-500
7. they are useable again

**Comment by dan200** [comment]
Can you provide me with a command computer script which replicates this bug.

**Comment by PokemonInLua** [comment]
seems to be fixed somehow in pr5

**Comment by dan200** [comment]
Then I'm putting this down to user error. The command code was not changed.

**Comment by zezioen** [comment]
http://www.computercraft.info/forums2/index.php?/topic/25597-18-computers-turning-black-and-not-displaying-any-information-even-though-theyre-still-working/

I think this bug has to be re-opened because it is happening again

**Comment by dan200** [comment]
See my previous comment about needing a repro case before I can investigate this

**Comment by zezioen** [comment]
Here ya go,

Place one computer with a multiblock monitor next (any side) to it and place a command computer
For the monitor comp run
pastebin get dNatfgCx moni
For the command comp run
pastebin get SZS8T9Zr bugy

This code is based on being in chunk 5 3 20 (first pos of the block filling is at 80 70 320)

It switched every 10 seconds and every time it causes the bug

**Comment by dan200** [comment]
Thanks

**Comment by dan200** [comment]
Can you re-test this in 1.77pr0?

**Comment by Wojbie** [comment]
Confirmed using with BombBloke code from https://github.com/dan200/ComputerCraft/issues/73
This and https://github.com/dan200/ComputerCraft/issues/73 seem to be same issue.

**Comment by Lordmau5** [comment]
I'll just drop in with some "help" on this issue.

Apparently it happens when a lot of blocks update in the same chunk.
2 videos that quickly show this:
https://i.lordmau5.com/1453414189-578
https://i.lordmau5.com/1453414492-580

Upon tank-building I am replacing all the normal blocks with custom blocks + tiles that "fake" their original render.
When I break the tank, they get set back to their normal blocks.
This means that there is a total of `7x7x7 - 5x5x5 = 125` blocks that get updated with a new block-state.

This is a video showing a `3x3x3 - 1 = 26` block-update.
Those and the monitors are in the same chunk.
https://i.lordmau5.com/1453415909-584

**Comment by dan200** [comment]
Fixed for 1.79
