### ISSUE TITLE
Print function stops printing if there is a nil present in the input array.

### ISSUE THREAD

**Issue by alekso56** [dan200/ComputerCraft#78]
Originally Kubuxu came up with this bug/feature request linked here:
https://github.com/Kubuxu/ComputercraftLua/commit/17dd0e427bb2bdf00845b86b3b4cc15c3467826c

VERSION:
1.41 to 1.76 (probably earlier too)
DESCRIPTION:
i typed print(1,2,nil,3) and it printed 1 2
EXPECTED RESULT:
1 2 nil 3
REPRODUCTION STEPS:
lua -> print(1,2,nil,3)

**Comment by KnightMiner** [comment]
This is intended, as any function that takes an unlimited number of parameters stops after the first nil. In fact, lua tables don't even keep nil values (converting any values after a nil to key indexed values rather than keeping the array), which makes taking all parameters after the nil next to impossible to do efficiently.

Find an alternate way to print the values, such as removing the value from the table entirely, or checking for nil before adding it.

**Comment by BombBloke** [comment]
Kubuxu says spec is to print the whole list, you say it's spec not to. Where do you guys get these specs from?

FWIW, I'd run a basic "for n = 1, whatever do" loop that manually indexes into the arg table on each iteration. Either use #arg or arg.n in place of "whatever", depending on the desired behaviour. As far as I'm aware, this'd be more efficient than calling an iterator function every time the loop repeats, wouldn't it be?

**Comment by KnightMiner** [comment]
My assumption is based on how the Lua manual seems to advise using `ipairs` for the illiterator for `...` parameters, combined with the fact that stopping upon reaching a `nil` value is expected behavior in most other ComputerCraft functions

**Comment by dan200** [comment]
Standalone lua is the reference implementation. Somebody test it in that?

**Comment by Wojbie** [comment]
According to http://www.lua.org/cgi-bin/demo
It prints word nil.

**Comment by dan200** [comment]
Sounds like a worthwhile change then. Will fix

**Comment by dan200** [comment]
Fixed for 1.77
