### ISSUE TITLE
Issue With Rendering Text On Screen (No texture packs) (Only Mod: Computercraft) (1.79pr1 Breaks it even worse (Completly Unplayable)

### ISSUE THREAD

**Issue by Silver07** [dan200/ComputerCraft#94]
Before: (ComputerCraft 1.78)
Link to Original Bug Thread (NOW LOCKED) 
http://www.computercraft.info/forums2/index.php?/topic/25927-issue-with-rendering-text-on-screen-no-texture-packs-only-mod-computercraft/
Posted Image
https://www.dropbox.com/s/m8tqlnek7zb2h9k/2016-02-10_15.27.32.png?dl=1
Now: (ComputerCraft 1.79pr1)
Posted Image
https://www.dropbox.com/s/kwqph6qy45sqkkn/2016-03-03_20.56.32.png?dl=1

Both of the images are displaying the same text, which can be shown by opening a fresh computer typing help, and hitting enter.

It basically Implexoded.

**Comment by dan200** [comment]
mind actually linking that thread?

**Comment by SquidDev** [comment]
[This one](http://www.computercraft.info/forums2/index.php?/topic/26114-issue-with-rendering-text-on-screen-no-texture-packs-only-mod-computercraft-179pr1-breaks-it-even-worse-completly-unplayable/)

**Comment by dan200** [comment]
Are you certain you don't still have Bomb Blokes' custom font installed? it's known to be incompatible

**Comment by BombBloke** [comment]
He says he's disabled it, and his screenshots do appear to be at the lower resolution. I've also released a new version which he says does much the same thing.

**Comment by Lignumm** [comment]
@Silver07 Have you tried updating your graphics drivers? I have a feeling this is caused by non-POT texture shenanigans, but that's just a wild guess.

**Comment by Silver07** [comment]
Thread linked, Graphics drivers are up to date, they just updated about 4 weeks ago, And the I had tested it with AND without the custom font, This issue is with 1.79pr1.

**Comment by Silver07** [comment]
For now i just use CC1.8 With the bomb blokes font, or I use ccemuredux.

**Comment by dan200** [comment]
So here's the deal:
The original bug was caused by the use of NPOT textures, and very old graphics cards not supporting them. The solution to that was to revert to a square POT texture, which fixed the bug for everyone who originally reported it. Your bug seems to be something different, and nobody else has reported it except you. There's nothing unusal about the font rendering anymore (it's just a 256x256 texture), so i'm clueless for ideas to how to fix this. I suspect it's something unique to your setup, but I can't think what. Can you try creating a completely new Minecraft install?

**Comment by Silver07** [comment]
I am just clueless, normal minecraft text renders perfectly fine,
at the moment, my laptop is having severe issues, i might have to reset it.
My graphics card updated, and now i can't even play Minecraft 1.8
but i can play tekkit? Also, the text issue only occurs in Minecraft 1.8 or above look perfect in other versions. I reinstalled minecraft, no fix, i might just go back to using my desktop for everything.
once i go get it from my friends house, my graphics card on my laptop, is apparenlty 10 years old, and the only drivers are for windows xp? Card is "ati mobility radeon x600". which, if i find my newer cards, i will change asap. Half my stuff is in storage.

**Comment by Lignumm** [comment]
@Silver07 Your card was launched in 2004, so it's 12 years old, even. In addition, AMD are known for making suboptimal OpenGL drivers. They have improved over the years but your GPU likely only supports ancient versions of the driver.

One change that was made in Minecraft 1.8 was the introduction of VBOs being used for rendering. Coincidentally, 2004 is roughly the time when VBOs were added to OpenGL, so you could imagine that your drivers might have a buggy implementation. Try turning off "Use VBOs" in video settings.

Though, I recommend you just use a newer GPU, since nobody will be bothered to fix a bug that only happens on 12 year old hardware.

**Comment by dan200** [comment]
As this issue seems to be unique to you, on very old hardware, and there's no obvious problem in the code, i'm going toclose this bug as "cannot reproduce". Sorry
